
spring.application.name=verve_guard

admin.username=${ADMIN_USERNAME}
admin.password=${ADMIN_PASSWORD}
admin.email=${ADMIN_EMAIL}

# =========================================
# Server
# =========================================
server.port=8080

# =========================================
# Datasource - PostgreSQL
# =========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/verve_guard
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================================
# JPA / Hibernate
# =========================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# =========================================
# Flyway
# =========================================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# =========================================
# JWT
# =========================================
jwt.secret=${JWT_SECRET}
# jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# =========================================
# Fraud Thresholds
# =========================================
fraud.amount.anomaly.multiplier=3.0

fraud.card.velocity.max-requests=3
fraud.card.velocity.window-minutes=5

fraud.ip.rate-limit.max-requests=5
fraud.ip.rate-limit.window-seconds=60
fraud.ip.multi-card.max-cards=5

fraud.repeat.offender.max-flags=5
fraud.repeat.offender.window-days=7

# =========================================
# Logging (optional tuning)
# =========================================
logging.level.org.springframework=INFO
logging.level.com.adetayo.verveguard=INFO

# =========================================
# Actuator
# =========================================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when_authorized